name: CI
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build & test layer
      run: make test_layer
